-- ============================================================
-- 05 · FASE 3 — Calidad y Gobierno (tal cual la propuesta)
--   5.1 Catálogo de 7 reglas de Data Quality + cuarentena
--   5.2 PIPELINE_AUDIT (una fila por corrida)
--   5.3 RBAC ~6 roles con mínimo privilegio
--   5.4 Masking de PII (nombre, RUC, email) — DS 016-2024-JUS
-- ============================================================

USE ROLE SYSADMIN;
USE WAREHOUSE WH_DEMO;
USE SCHEMA DWH_DEMO.GOVERNANCE;

-- -----------------------------------------------------------
-- 5.1 Catálogo formal de reglas DQ + cuarentena
-- -----------------------------------------------------------
CREATE OR REPLACE TABLE DQ_RULES (
    RULE_ID       NUMBER,
    RULE_NAME     VARCHAR,
    RULE_TYPE     VARCHAR,     -- las 7 categorías de la propuesta
    TARGET_TABLE  VARCHAR,
    RULE_SQL_DESC VARCHAR,
    SEVERITY      VARCHAR      -- ERROR = cuarentena · WARN = solo se registra
);

INSERT INTO DQ_RULES VALUES
 (1,'Fecha de documento obligatoria','OBLIGATORIO','STG_SALES_ORDERS','ORDER_DATE IS NOT NULL','ERROR'),
 (2,'Importe obligatorio y numérico','OBLIGATORIO','STG_SALES_ORDERS','NET_AMOUNT IS NOT NULL','ERROR'),
 (3,'Unicidad de clave orden+posición','UNICIDAD','STG_SALES_ORDERS','(ORDER_ID, ITEM_NO) únicos','ERROR'),
 (4,'Cliente existe en maestro','INTEGRIDAD_REF','STG_SALES_ORDERS','CUSTOMER_ID en DIM_CUSTOMER','ERROR'),
 (5,'Cantidad en rango razonable','RANGO','STG_SALES_ORDERS','QUANTITY BETWEEN 0 AND 100000','WARN'),
 (6,'RUC con formato válido (11 dígitos)','FORMATO','STG_CUSTOMERS','TAX_ID REGEXP 11 dígitos','WARN'),
 (7,'Factura ≤ cantidad de la orden','CONSISTENCIA_CRUZADA','STG_BILLING','FKIMG <= KWMENG de la orden ref.','WARN');

-- Cuarentena: los registros que fallan NO se descartan en silencio
CREATE OR REPLACE TABLE DQ_QUARANTINE (
    QUARANTINE_ID  NUMBER IDENTITY,
    RULE_ID        NUMBER,
    SOURCE_TABLE   VARCHAR,
    RECORD_KEY     VARCHAR,
    RECORD_PAYLOAD VARIANT,       -- el registro completo, para corregir en la fuente
    DETECTED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUS         VARCHAR DEFAULT 'PENDIENTE'   -- PENDIENTE / CORREGIDO / DESCARTADO
);

-- Procedimiento que corre el catálogo completo y aísla lo que falla
CREATE OR REPLACE PROCEDURE SP_RUN_DQ_CHECKS()
RETURNS VARCHAR
LANGUAGE SQL
AS
BEGIN
    -- Regla 1: fechas nulas/basura
    INSERT INTO DQ_QUARANTINE (RULE_ID, SOURCE_TABLE, RECORD_KEY, RECORD_PAYLOAD)
    SELECT 1, 'STG_SALES_ORDERS', ORDER_ID || '-' || ITEM_NO, OBJECT_CONSTRUCT(*)
    FROM DWH_DEMO.STAGING.STG_SALES_ORDERS WHERE ORDER_DATE IS NULL;

    -- Regla 2: importes nulos
    INSERT INTO DQ_QUARANTINE (RULE_ID, SOURCE_TABLE, RECORD_KEY, RECORD_PAYLOAD)
    SELECT 2, 'STG_SALES_ORDERS', ORDER_ID || '-' || ITEM_NO, OBJECT_CONSTRUCT(*)
    FROM DWH_DEMO.STAGING.STG_SALES_ORDERS WHERE NET_AMOUNT IS NULL;

    -- Regla 3: duplicados de clave natural
    INSERT INTO DQ_QUARANTINE (RULE_ID, SOURCE_TABLE, RECORD_KEY, RECORD_PAYLOAD)
    SELECT 3, 'STG_SALES_ORDERS', ORDER_ID || '-' || ITEM_NO, OBJECT_CONSTRUCT(*)
    FROM DWH_DEMO.STAGING.STG_SALES_ORDERS
    QUALIFY COUNT(*) OVER (PARTITION BY ORDER_ID, ITEM_NO) > 1
        AND ROW_NUMBER() OVER (PARTITION BY ORDER_ID, ITEM_NO ORDER BY _LOADED_AT) > 1;

    -- Regla 4: huérfanos (cliente inexistente)
    INSERT INTO DQ_QUARANTINE (RULE_ID, SOURCE_TABLE, RECORD_KEY, RECORD_PAYLOAD)
    SELECT 4, 'STG_SALES_ORDERS', s.ORDER_ID || '-' || s.ITEM_NO, OBJECT_CONSTRUCT(s.*)
    FROM DWH_DEMO.STAGING.STG_SALES_ORDERS s
    LEFT JOIN DWH_DEMO.CURATED.DIM_CUSTOMER c
      ON c.CUSTOMER_ID = s.CUSTOMER_ID AND c.IS_CURRENT
    WHERE c.CUSTOMER_ID IS NULL;

    -- Regla 5: rangos
    INSERT INTO DQ_QUARANTINE (RULE_ID, SOURCE_TABLE, RECORD_KEY, RECORD_PAYLOAD)
    SELECT 5, 'STG_SALES_ORDERS', ORDER_ID || '-' || ITEM_NO, OBJECT_CONSTRUCT(*)
    FROM DWH_DEMO.STAGING.STG_SALES_ORDERS
    WHERE QUANTITY IS NOT NULL AND QUANTITY NOT BETWEEN 0 AND 100000;

    -- Regla 6: formato de RUC
    INSERT INTO DQ_QUARANTINE (RULE_ID, SOURCE_TABLE, RECORD_KEY, RECORD_PAYLOAD)
    SELECT 6, 'STG_CUSTOMERS', CUSTOMER_ID, OBJECT_CONSTRUCT(*)
    FROM DWH_DEMO.STAGING.STG_CUSTOMERS
    WHERE TAX_ID IS NULL OR NOT TAX_ID REGEXP '^[0-9]{11}$';

    -- Regla 7: consistencia cruzada factura vs orden
    INSERT INTO DQ_QUARANTINE (RULE_ID, SOURCE_TABLE, RECORD_KEY, RECORD_PAYLOAD)
    SELECT 7, 'STG_BILLING', b.BILLING_ID || '-' || b.ITEM_NO, OBJECT_CONSTRUCT(b.*)
    FROM DWH_DEMO.STAGING.STG_BILLING b
    JOIN DWH_DEMO.STAGING.STG_SALES_ORDERS s
      ON s.ORDER_ID = b.REF_ORDER_ID AND s.ITEM_NO = b.ITEM_NO
    WHERE b.QUANTITY > s.QUANTITY * 1.05;    -- tolerancia 5%

    RETURN 'DQ checks ejecutados. Ver GOVERNANCE.DQ_QUARANTINE';
END;

CALL SP_RUN_DQ_CHECKS();

-- Vista resumen para mostrar en la demo: "la calidad deja de ser un acto de fe"
CREATE OR REPLACE VIEW V_DQ_DASHBOARD AS
SELECT r.RULE_ID, r.RULE_NAME, r.RULE_TYPE, r.SEVERITY,
       COUNT(q.QUARANTINE_ID) AS REGISTROS_AFECTADOS,
       MAX(q.DETECTED_AT)     AS ULTIMA_DETECCION
FROM DQ_RULES r
LEFT JOIN DQ_QUARANTINE q ON q.RULE_ID = r.RULE_ID
GROUP BY 1,2,3,4
ORDER BY r.RULE_ID;

-- -----------------------------------------------------------
-- 5.2 PIPELINE_AUDIT — una fila por corrida
-- -----------------------------------------------------------
CREATE OR REPLACE TABLE PIPELINE_AUDIT (
    RUN_ID         NUMBER IDENTITY,
    PIPELINE_NAME  VARCHAR,
    SOURCE_NAME    VARCHAR,
    STARTED_AT     TIMESTAMP_NTZ,
    FINISHED_AT    TIMESTAMP_NTZ,
    ROWS_READ      NUMBER,
    ROWS_INSERTED  NUMBER,
    ROWS_REJECTED  NUMBER,
    STATUS         VARCHAR,      -- OK / WARN / ERROR
    DETAIL         VARCHAR
);

-- Registro de ejemplo de la corrida de la demo (en producción lo escribe cada task)
INSERT INTO PIPELINE_AUDIT (PIPELINE_NAME, SOURCE_NAME, STARTED_AT, FINISHED_AT,
                            ROWS_READ, ROWS_INSERTED, ROWS_REJECTED, STATUS, DETAIL)
SELECT 'LOAD_FACT_SALES_ORDERS', 'CDS I_SalesDocument (simulado)',
       DATEADD(minute,-4,CURRENT_TIMESTAMP()), CURRENT_TIMESTAMP(),
       (SELECT COUNT(*) FROM DWH_DEMO.STAGING.STG_SALES_ORDERS),
       (SELECT COUNT(*) FROM DWH_DEMO.CURATED.FACT_SALES_ORDERS),
       (SELECT COUNT(*) FROM DQ_QUARANTINE WHERE SOURCE_TABLE='STG_SALES_ORDERS'),
       'OK', 'Carga inicial demo';

-- -----------------------------------------------------------
-- 5.3 RBAC — 6 roles con mínimo privilegio
-- (requiere SECURITYADMIN; en la demo alcanza con crearlos una vez)
-- -----------------------------------------------------------
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS R_DATA_ENGINEER;   -- todo el pipeline
CREATE ROLE IF NOT EXISTS R_DATA_ANALYST;    -- lee CURATED, ve PII
CREATE ROLE IF NOT EXISTS R_ANALYST_MASKED;  -- lee CURATED, PII enmascarada
CREATE ROLE IF NOT EXISTS R_GERENCIA;        -- lee solo vistas de KPI
CREATE ROLE IF NOT EXISTS R_AUDITOR;         -- lee GOVERNANCE (auditoría y DQ)
CREATE ROLE IF NOT EXISTS R_ML_SERVICE;      -- lee CURATED para modelos

GRANT USAGE ON WAREHOUSE WH_DEMO TO ROLE R_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_DEMO TO ROLE R_DATA_ANALYST;
GRANT USAGE ON WAREHOUSE WH_DEMO TO ROLE R_ANALYST_MASKED;
GRANT USAGE ON WAREHOUSE WH_DEMO TO ROLE R_GERENCIA;
GRANT USAGE ON WAREHOUSE WH_DEMO TO ROLE R_AUDITOR;
GRANT USAGE ON WAREHOUSE WH_DEMO TO ROLE R_ML_SERVICE;

GRANT USAGE ON DATABASE DWH_DEMO TO ROLE R_DATA_ENGINEER;
GRANT USAGE ON DATABASE DWH_DEMO TO ROLE R_DATA_ANALYST;
GRANT USAGE ON DATABASE DWH_DEMO TO ROLE R_ANALYST_MASKED;
GRANT USAGE ON DATABASE DWH_DEMO TO ROLE R_GERENCIA;
GRANT USAGE ON DATABASE DWH_DEMO TO ROLE R_AUDITOR;
GRANT USAGE ON DATABASE DWH_DEMO TO ROLE R_ML_SERVICE;

-- Engineer: dueño operativo de todos los schemas
GRANT ALL ON SCHEMA DWH_DEMO.RAW        TO ROLE R_DATA_ENGINEER;
GRANT ALL ON SCHEMA DWH_DEMO.STAGING    TO ROLE R_DATA_ENGINEER;
GRANT ALL ON SCHEMA DWH_DEMO.CURATED    TO ROLE R_DATA_ENGINEER;
GRANT ALL ON SCHEMA DWH_DEMO.GOVERNANCE TO ROLE R_DATA_ENGINEER;

-- Analistas: solo CURATED, solo lectura (+ objetos futuros)
GRANT USAGE ON SCHEMA DWH_DEMO.CURATED TO ROLE R_DATA_ANALYST;
GRANT SELECT ON ALL TABLES    IN SCHEMA DWH_DEMO.CURATED TO ROLE R_DATA_ANALYST;
GRANT SELECT ON ALL VIEWS     IN SCHEMA DWH_DEMO.CURATED TO ROLE R_DATA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DWH_DEMO.CURATED TO ROLE R_DATA_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA DWH_DEMO.CURATED TO ROLE R_DATA_ANALYST;

GRANT USAGE ON SCHEMA DWH_DEMO.CURATED TO ROLE R_ANALYST_MASKED;
GRANT SELECT ON ALL TABLES    IN SCHEMA DWH_DEMO.CURATED TO ROLE R_ANALYST_MASKED;
GRANT SELECT ON ALL VIEWS     IN SCHEMA DWH_DEMO.CURATED TO ROLE R_ANALYST_MASKED;

-- Gerencia: solo las vistas de KPI
GRANT USAGE ON SCHEMA DWH_DEMO.CURATED TO ROLE R_GERENCIA;
GRANT SELECT ON VIEW DWH_DEMO.CURATED.V_VENTAS_MENSUALES  TO ROLE R_GERENCIA;
GRANT SELECT ON VIEW DWH_DEMO.CURATED.V_CUMPLIMIENTO_PPTO TO ROLE R_GERENCIA;

-- Auditor: GOVERNANCE en lectura
GRANT USAGE ON SCHEMA DWH_DEMO.GOVERNANCE TO ROLE R_AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA DWH_DEMO.GOVERNANCE TO ROLE R_AUDITOR;
GRANT SELECT ON ALL VIEWS  IN SCHEMA DWH_DEMO.GOVERNANCE TO ROLE R_AUDITOR;

-- ML: CURATED en lectura
GRANT USAGE ON SCHEMA DWH_DEMO.CURATED TO ROLE R_ML_SERVICE;
GRANT SELECT ON ALL TABLES IN SCHEMA DWH_DEMO.CURATED TO ROLE R_ML_SERVICE;
GRANT SELECT ON ALL VIEWS  IN SCHEMA DWH_DEMO.CURATED TO ROLE R_ML_SERVICE;

-- Asignate los roles a tu usuario para poder demostrar el cambio de rol
-- GRANT ROLE R_DATA_ANALYST   TO USER <tu_usuario>;
-- GRANT ROLE R_ANALYST_MASKED TO USER <tu_usuario>;
-- GRANT ROLE R_GERENCIA       TO USER <tu_usuario>;

-- -----------------------------------------------------------
-- 5.4 Masking de PII — nombre, RUC, email
-- (Dynamic Data Masking requiere edición Enterprise)
-- -----------------------------------------------------------
USE ROLE SYSADMIN;   -- o ACCOUNTADMIN si SYSADMIN no tiene APPLY MASKING POLICY
USE SCHEMA DWH_DEMO.GOVERNANCE;

CREATE OR REPLACE MASKING POLICY MP_PII_STRING AS (val VARCHAR)
RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('R_DATA_ANALYST','R_DATA_ENGINEER','ACCOUNTADMIN','SYSADMIN')
            THEN val
        ELSE '***PROTEGIDO***'
    END;

CREATE OR REPLACE MASKING POLICY MP_PII_EMAIL AS (val VARCHAR)
RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('R_DATA_ANALYST','R_DATA_ENGINEER','ACCOUNTADMIN','SYSADMIN')
            THEN val
        ELSE REGEXP_REPLACE(val, '^[^@]+', '*****')   -- deja el dominio visible
    END;

ALTER TABLE DWH_DEMO.CURATED.DIM_CUSTOMER MODIFY COLUMN CUSTOMER_NAME SET MASKING POLICY MP_PII_STRING;
ALTER TABLE DWH_DEMO.CURATED.DIM_CUSTOMER MODIFY COLUMN TAX_ID        SET MASKING POLICY MP_PII_STRING;
ALTER TABLE DWH_DEMO.CURATED.DIM_CUSTOMER MODIFY COLUMN EMAIL         SET MASKING POLICY MP_PII_EMAIL;

-- Momento demo: con SYSADMIN ves los datos; con R_ANALYST_MASKED, no.
-- USE ROLE R_ANALYST_MASKED;
-- SELECT CUSTOMER_NAME, TAX_ID, EMAIL FROM DWH_DEMO.CURATED.DIM_CUSTOMER LIMIT 5;
